apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: special-wolverine-nodejs 
  janus-idp.io/tekton: special-wolverine-nodejs
  backstage.io/kubernetes-id: special-wolverine-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: special-wolverine-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  